#!/bin/bash

# Setup correct refresh rate
xrandr --output DVI-D-0 --mode 1920x1080 --rate 144

# Start picom compositor
picom -b

# Setup Wallpaper and gen color scheme
feh --bg-scale $HOME/.config/dots/wallpaper/wallpaper.jpg &
wal -i $HOME/.config/dots/wallpaper/wallpaper.jpg &
. "${HOME}/.cache/wal/colors.sh"

bspc monitor -d I II III IV

# Configure Colors
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

# Setup Style
bspc config border_width 0
bspc config window_gap 32
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config automatic_scheme spiral

# Pointer Settings
bspc config pointer_motion_interval 7
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bsoc config focus_follows_pointer true
xsetroot -cursor_name left_ptr

# Start Polybar, Dunst, sxhkd
pkill polybar; polybar --config=$HOME/.config/polybar/config.ini epicbar 2>&1 | tee -a /tmp/polybar.log & disown 
pkill dunst; dunst &
pkill sxhkd; sxhkd &
pkill unclutter; unclutter -idle 2 -b &
